RM := rm -rf
BRIDGE_EXE := studio-mdk-bridge.exe
UV4_EXE := "D:\Keil_v5\UV4\UV4.exe"
UVPROJX_LOC := "E:\Embebded\STM32\STM32H7\LCD+LORA\MDK-ARM\STM32H750VBT6.uvprojx"

.PHONY: mdk_all

mdk_all:
	-$(BRIDGE_EXE) --build --uv4-path $(UV4_EXE) $(UVPROJX_LOC)

mdk_clean:
	-@$(RM) *
	@echo 'success'

